id: A9C699347
title: Verses on the Buddha's Previous Lives
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:09:36.814797
  last_modified_at: 2022-03-01 02:09:36.814801
